export enum CatechizingActionTypes {
  SET_ALL = 'SET_ALL',
  RESET = 'RESET',
  SET_NAME = 'SET_NAME',
  SET_BIRTHDAY = 'SET_BIRTHDAY',
  SET_ADDRESS = 'SET_ADDRESS',
  SET_PERSON_WITH_SPECIAL_NEEDS = 'SET_PERSON_WITH_SPECIAL_NEEDS',
  SET_HAS_RECEIVED_BAPTISM = 'SET_HAS_RECEIVED_BAPTISM',
  SET_HAS_RECEIVED_EUCHARIST = 'SET_HAS_RECEIVED_EUCHARIST',
  SET_HAS_RECEIVED_MARRIAGE = 'SET_HAS_RECEIVED_MARRIAGE',
}
