export enum ClassroomActionTypes {
  SET_ALL = 'SET_ALL',
  RESET = 'RESET',
  SET_ROOM_NUMBER = 'SET_ROOM_NUMBER',
  SET_SEGMENT = 'SET_SEGMENT',
  SET_STARTED_AT = 'SET_STARTED_AT',
  SET_CATECHISTS = 'SET_CATECHISTS',
}
