export enum CatechistActionTypes {
  SET_ALL = 'SET_ALL',
  RESET = 'RESET',
  SET_NAME = 'SET_NAME',
  SET_BIRTHDAY = 'SET_BIRTHDAY',
  SET_ADDRESS = 'SET_ADDRESS',
  SET_PHONE = 'SET_PHONE',
  SET_EMAIL = 'SET_EMAIL',
  SET_CATECHIST_TO_CLASSROOM = 'SET_CATECHIST_TO_CLASSROOM',
  SET_HAS_RECEIVED_BAPTISM = 'SET_HAS_RECEIVED_BAPTISM',
  SET_HAS_RECEIVED_EUCHARIST = 'SET_HAS_RECEIVED_EUCHARIST',
  SET_HAS_RECEIVED_CONFIRMATION = 'SET_HAS_RECEIVED_CONFIRMATION',
  SET_HAS_RECEIVED_MARRIAGE = 'SET_HAS_RECEIVED_MARRIAGE',
}
